import { NextRequest, NextResponse } from 'next/server'
import twilio from 'twilio'

interface Recipe {
  name: string
  ingredients: string[]
  instructions: string
  cookingTime: string
  servings: string
}

export async function POST(request: NextRequest) {
  try {
    const { phoneNumber, recipes } = await request.json()

    if (!phoneNumber || !recipes || recipes.length === 0) {
      return NextResponse.json(
        { error: 'Phone number and recipes are required' },
        { status: 400 }
      )
    }

    const accountSid = process.env.TWILIO_ACCOUNT_SID
    const authToken = process.env.TWILIO_AUTH_TOKEN
    const whatsappNumber = process.env.TWILIO_WHATSAPP_NUMBER

    if (!accountSid || !authToken || !whatsappNumber) {
      return NextResponse.json(
        { error: 'WhatsApp integration not configured. Please set up Twilio credentials in environment variables.' },
        { status: 500 }
      )
    }

    const client = twilio(accountSid, authToken)

    // Format recipes into WhatsApp message
    let message = '🍳 *Your Leftover Recipe Ideas* 🍳\n\n'

    recipes.forEach((recipe: Recipe, index: number) => {
      const emoji = index === 0 ? '🥇' : index === 1 ? '🥈' : '🥉'
      message += `${emoji} *${recipe.name}*\n`
      message += `⏱️ Time: ${recipe.cookingTime}\n`
      message += `👥 Servings: ${recipe.servings}\n\n`
      message += `*Ingredients:*\n`
      recipe.ingredients.forEach((ingredient: string) => {
        message += `• ${ingredient}\n`
      })
      message += `\n*Instructions:*\n${recipe.instructions}\n\n`
      message += '─────────────────\n\n'
    })

    message += 'Enjoy cooking! 👨‍🍳👩‍🍳\n'
    message += '\nGenerated by Leftover Recipe Generator'

    // Send WhatsApp message via Twilio
    await client.messages.create({
      from: `whatsapp:${whatsappNumber}`,
      to: `whatsapp:${phoneNumber}`,
      body: message,
    })

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error('Error sending WhatsApp message:', error)
    return NextResponse.json(
      { error: 'Failed to send WhatsApp message. Please check your phone number format and Twilio configuration.' },
      { status: 500 }
    )
  }
}
